# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83cc3f7c90c5913bd50b963fa6f4b504fd900c4a2ddd46a7067e5690f0836058891c6c7f42cddb9524b9ae0bf09669d1a5f3f8b7d752be530c59e0c90f234f7e

test:
  secret_key_base: 433458197a57164a111226cea7e4480ed922da62ce586b98f206ddd6f42c59b35f1c7058c94c2d3ba4f4d3e312325dfe7aa78b13e4815b5c1b257df4dce90508

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
